name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: install
        run: |
          pip install -e .
      - name: testlensing
        run: |
          python lenspyx/tests/lensing.py
          python lenspyx/tests/splits.py
          python lenspyx/tests/test_funkypointing.py
          python lenspyx/tests/cmplxvsreal.py