name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10, 3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip3 install --user git+https://gitlab.mpcdf.mpg.de/mtr/ducc.git@ducc0
      - name: install
        run: |
          pip install -e . --user
      - name: testlensing
        run: |
          python lenspyx/tests/lensing.py
          python lenspyx/tests/splits.py
          python lenspyx/tests/test_funkypointing.py
          python lenspyx/tests/cmplxvsreal.py